### ISSUE TITLE
save folder location

### ISSUE THREAD

**Issue by cmod31** [tvandoorn/longvinter-docker-server#3]
Hey where do i access the save folder of the longvinter server the folder for longvinter with engine and game.ini and all that is completely missing

**Comment by tvandoorn** [comment]
Hi, the docker setup uses a Docker volume by default, this means your server files are not accessible directly. For more information and how to store the server files in a folder, see https://github.com/tvandoorn/longvinter-docker-server#setting-up-the-data-directory.

Also note that the Game.ini file will be overwritten every time the container starts. It creates the Game.ini file based on the environment variables (settings) that are included in the docker-compose.yaml file. So changing the Game.ini file directly will not do anything, but you can alter the settings using the docker-compose.yaml file. See https://github.com/tvandoorn/longvinter-docker-server#configuring-the-server-settings for more info on this. Make sure to run docker-compose up -d after altering the settings.
